services:
  - type: web
    name: tt4-2920-backend
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        fromService:
          name: tt4-2920-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: tt4-2920-frontend
    runtime: docker
    rootDir: ./frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_URL
        fromService:
          name: tt4-2920-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
